package guyuanjun.com.myappdemo.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import guyuanjun.com.myappdemo.bean.AttentionInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ATTENTION_INFO".
*/
public class AttentionInfoDao extends AbstractDao<AttentionInfo, Long> {

    public static final String TABLENAME = "ATTENTION_INFO";

    /**
     * Properties of entity AttentionInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property User_id = new Property(1, Long.class, "user_id", false, "USER_ID");
        public final static Property Item_id = new Property(2, Long.class, "item_id", false, "ITEM_ID");
        public final static Property Attention_time = new Property(3, java.util.Date.class, "attention_time", false, "ATTENTION_TIME");
        public final static Property Has_attentioned = new Property(4, boolean.class, "has_attentioned", false, "HAS_ATTENTIONED");
    }


    public AttentionInfoDao(DaoConfig config) {
        super(config);
    }
    
    public AttentionInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ATTENTION_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"USER_ID\" INTEGER," + // 1: user_id
                "\"ITEM_ID\" INTEGER," + // 2: item_id
                "\"ATTENTION_TIME\" INTEGER," + // 3: attention_time
                "\"HAS_ATTENTIONED\" INTEGER NOT NULL );"); // 4: has_attentioned
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ATTENTION_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AttentionInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long user_id = entity.getUser_id();
        if (user_id != null) {
            stmt.bindLong(2, user_id);
        }
 
        Long item_id = entity.getItem_id();
        if (item_id != null) {
            stmt.bindLong(3, item_id);
        }
 
        java.util.Date attention_time = entity.getAttention_time();
        if (attention_time != null) {
            stmt.bindLong(4, attention_time.getTime());
        }
        stmt.bindLong(5, entity.getHas_attentioned() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AttentionInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long user_id = entity.getUser_id();
        if (user_id != null) {
            stmt.bindLong(2, user_id);
        }
 
        Long item_id = entity.getItem_id();
        if (item_id != null) {
            stmt.bindLong(3, item_id);
        }
 
        java.util.Date attention_time = entity.getAttention_time();
        if (attention_time != null) {
            stmt.bindLong(4, attention_time.getTime());
        }
        stmt.bindLong(5, entity.getHas_attentioned() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public AttentionInfo readEntity(Cursor cursor, int offset) {
        AttentionInfo entity = new AttentionInfo();
        readEntity(cursor, entity, offset);
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AttentionInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUser_id(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setItem_id(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setAttention_time(cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)));
        entity.setHas_attentioned(cursor.getShort(offset + 4) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(AttentionInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(AttentionInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(AttentionInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
