package guyuanjun.com.myappdemo.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import guyuanjun.com.myappdemo.bean.AdminInfo;
import guyuanjun.com.myappdemo.bean.AnswearInfo;
import guyuanjun.com.myappdemo.bean.AttentionInfo;
import guyuanjun.com.myappdemo.bean.CollectInfo;
import guyuanjun.com.myappdemo.bean.CommentInfo;
import guyuanjun.com.myappdemo.bean.FanInfo;
import guyuanjun.com.myappdemo.bean.LookupInfo;
import guyuanjun.com.myappdemo.bean.MobileInfo;
import guyuanjun.com.myappdemo.bean.NewsItemInfo;
import guyuanjun.com.myappdemo.bean.PushInfo;
import guyuanjun.com.myappdemo.bean.Student;
import guyuanjun.com.myappdemo.bean.UserInfo;
import guyuanjun.com.myappdemo.bean.WeitoutiaoInfo;

import guyuanjun.com.myappdemo.greendao.AdminInfoDao;
import guyuanjun.com.myappdemo.greendao.AnswearInfoDao;
import guyuanjun.com.myappdemo.greendao.AttentionInfoDao;
import guyuanjun.com.myappdemo.greendao.CollectInfoDao;
import guyuanjun.com.myappdemo.greendao.CommentInfoDao;
import guyuanjun.com.myappdemo.greendao.FanInfoDao;
import guyuanjun.com.myappdemo.greendao.LookupInfoDao;
import guyuanjun.com.myappdemo.greendao.MobileInfoDao;
import guyuanjun.com.myappdemo.greendao.NewsItemInfoDao;
import guyuanjun.com.myappdemo.greendao.PushInfoDao;
import guyuanjun.com.myappdemo.greendao.StudentDao;
import guyuanjun.com.myappdemo.greendao.UserInfoDao;
import guyuanjun.com.myappdemo.greendao.WeitoutiaoInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig adminInfoDaoConfig;
    private final DaoConfig answearInfoDaoConfig;
    private final DaoConfig attentionInfoDaoConfig;
    private final DaoConfig collectInfoDaoConfig;
    private final DaoConfig commentInfoDaoConfig;
    private final DaoConfig fanInfoDaoConfig;
    private final DaoConfig lookupInfoDaoConfig;
    private final DaoConfig mobileInfoDaoConfig;
    private final DaoConfig newsItemInfoDaoConfig;
    private final DaoConfig pushInfoDaoConfig;
    private final DaoConfig studentDaoConfig;
    private final DaoConfig userInfoDaoConfig;
    private final DaoConfig weitoutiaoInfoDaoConfig;

    private final AdminInfoDao adminInfoDao;
    private final AnswearInfoDao answearInfoDao;
    private final AttentionInfoDao attentionInfoDao;
    private final CollectInfoDao collectInfoDao;
    private final CommentInfoDao commentInfoDao;
    private final FanInfoDao fanInfoDao;
    private final LookupInfoDao lookupInfoDao;
    private final MobileInfoDao mobileInfoDao;
    private final NewsItemInfoDao newsItemInfoDao;
    private final PushInfoDao pushInfoDao;
    private final StudentDao studentDao;
    private final UserInfoDao userInfoDao;
    private final WeitoutiaoInfoDao weitoutiaoInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        adminInfoDaoConfig = daoConfigMap.get(AdminInfoDao.class).clone();
        adminInfoDaoConfig.initIdentityScope(type);

        answearInfoDaoConfig = daoConfigMap.get(AnswearInfoDao.class).clone();
        answearInfoDaoConfig.initIdentityScope(type);

        attentionInfoDaoConfig = daoConfigMap.get(AttentionInfoDao.class).clone();
        attentionInfoDaoConfig.initIdentityScope(type);

        collectInfoDaoConfig = daoConfigMap.get(CollectInfoDao.class).clone();
        collectInfoDaoConfig.initIdentityScope(type);

        commentInfoDaoConfig = daoConfigMap.get(CommentInfoDao.class).clone();
        commentInfoDaoConfig.initIdentityScope(type);

        fanInfoDaoConfig = daoConfigMap.get(FanInfoDao.class).clone();
        fanInfoDaoConfig.initIdentityScope(type);

        lookupInfoDaoConfig = daoConfigMap.get(LookupInfoDao.class).clone();
        lookupInfoDaoConfig.initIdentityScope(type);

        mobileInfoDaoConfig = daoConfigMap.get(MobileInfoDao.class).clone();
        mobileInfoDaoConfig.initIdentityScope(type);

        newsItemInfoDaoConfig = daoConfigMap.get(NewsItemInfoDao.class).clone();
        newsItemInfoDaoConfig.initIdentityScope(type);

        pushInfoDaoConfig = daoConfigMap.get(PushInfoDao.class).clone();
        pushInfoDaoConfig.initIdentityScope(type);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        weitoutiaoInfoDaoConfig = daoConfigMap.get(WeitoutiaoInfoDao.class).clone();
        weitoutiaoInfoDaoConfig.initIdentityScope(type);

        adminInfoDao = new AdminInfoDao(adminInfoDaoConfig, this);
        answearInfoDao = new AnswearInfoDao(answearInfoDaoConfig, this);
        attentionInfoDao = new AttentionInfoDao(attentionInfoDaoConfig, this);
        collectInfoDao = new CollectInfoDao(collectInfoDaoConfig, this);
        commentInfoDao = new CommentInfoDao(commentInfoDaoConfig, this);
        fanInfoDao = new FanInfoDao(fanInfoDaoConfig, this);
        lookupInfoDao = new LookupInfoDao(lookupInfoDaoConfig, this);
        mobileInfoDao = new MobileInfoDao(mobileInfoDaoConfig, this);
        newsItemInfoDao = new NewsItemInfoDao(newsItemInfoDaoConfig, this);
        pushInfoDao = new PushInfoDao(pushInfoDaoConfig, this);
        studentDao = new StudentDao(studentDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);
        weitoutiaoInfoDao = new WeitoutiaoInfoDao(weitoutiaoInfoDaoConfig, this);

        registerDao(AdminInfo.class, adminInfoDao);
        registerDao(AnswearInfo.class, answearInfoDao);
        registerDao(AttentionInfo.class, attentionInfoDao);
        registerDao(CollectInfo.class, collectInfoDao);
        registerDao(CommentInfo.class, commentInfoDao);
        registerDao(FanInfo.class, fanInfoDao);
        registerDao(LookupInfo.class, lookupInfoDao);
        registerDao(MobileInfo.class, mobileInfoDao);
        registerDao(NewsItemInfo.class, newsItemInfoDao);
        registerDao(PushInfo.class, pushInfoDao);
        registerDao(Student.class, studentDao);
        registerDao(UserInfo.class, userInfoDao);
        registerDao(WeitoutiaoInfo.class, weitoutiaoInfoDao);
    }
    
    public void clear() {
        adminInfoDaoConfig.clearIdentityScope();
        answearInfoDaoConfig.clearIdentityScope();
        attentionInfoDaoConfig.clearIdentityScope();
        collectInfoDaoConfig.clearIdentityScope();
        commentInfoDaoConfig.clearIdentityScope();
        fanInfoDaoConfig.clearIdentityScope();
        lookupInfoDaoConfig.clearIdentityScope();
        mobileInfoDaoConfig.clearIdentityScope();
        newsItemInfoDaoConfig.clearIdentityScope();
        pushInfoDaoConfig.clearIdentityScope();
        studentDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
        weitoutiaoInfoDaoConfig.clearIdentityScope();
    }

    public AdminInfoDao getAdminInfoDao() {
        return adminInfoDao;
    }

    public AnswearInfoDao getAnswearInfoDao() {
        return answearInfoDao;
    }

    public AttentionInfoDao getAttentionInfoDao() {
        return attentionInfoDao;
    }

    public CollectInfoDao getCollectInfoDao() {
        return collectInfoDao;
    }

    public CommentInfoDao getCommentInfoDao() {
        return commentInfoDao;
    }

    public FanInfoDao getFanInfoDao() {
        return fanInfoDao;
    }

    public LookupInfoDao getLookupInfoDao() {
        return lookupInfoDao;
    }

    public MobileInfoDao getMobileInfoDao() {
        return mobileInfoDao;
    }

    public NewsItemInfoDao getNewsItemInfoDao() {
        return newsItemInfoDao;
    }

    public PushInfoDao getPushInfoDao() {
        return pushInfoDao;
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

    public WeitoutiaoInfoDao getWeitoutiaoInfoDao() {
        return weitoutiaoInfoDao;
    }

}
