package guyuanjun.com.myappdemo.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import guyuanjun.com.myappdemo.bean.WeitoutiaoInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "WEITOUTIAO_INFO".
*/
public class WeitoutiaoInfoDao extends AbstractDao<WeitoutiaoInfo, Long> {

    public static final String TABLENAME = "WEITOUTIAO_INFO";

    /**
     * Properties of entity WeitoutiaoInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property User_id = new Property(1, Long.class, "user_id", false, "USER_ID");
        public final static Property Username = new Property(2, String.class, "username", false, "USERNAME");
        public final static Property Where = new Property(3, String.class, "where", false, "WHERE");
        public final static Property Time = new Property(4, java.util.Date.class, "time", false, "TIME");
        public final static Property Img_path = new Property(5, String.class, "img_path", false, "IMG_PATH");
        public final static Property Img_path_list = new Property(6, String.class, "img_path_list", false, "IMG_PATH_LIST");
        public final static Property Content = new Property(7, String.class, "content", false, "CONTENT");
        public final static Property Flag_type = new Property(8, int.class, "flag_type", false, "FLAG_TYPE");
        public final static Property Read_num = new Property(9, Integer.class, "read_num", false, "READ_NUM");
        public final static Property Praise_num = new Property(10, Integer.class, "praise_num", false, "PRAISE_NUM");
        public final static Property Comment_num = new Property(11, Integer.class, "comment_num", false, "COMMENT_NUM");
        public final static Property Has_praised = new Property(12, Boolean.class, "has_praised", false, "HAS_PRAISED");
    }


    public WeitoutiaoInfoDao(DaoConfig config) {
        super(config);
    }
    
    public WeitoutiaoInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"WEITOUTIAO_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"USER_ID\" INTEGER," + // 1: user_id
                "\"USERNAME\" TEXT," + // 2: username
                "\"WHERE\" TEXT," + // 3: where
                "\"TIME\" INTEGER," + // 4: time
                "\"IMG_PATH\" TEXT," + // 5: img_path
                "\"IMG_PATH_LIST\" TEXT," + // 6: img_path_list
                "\"CONTENT\" TEXT," + // 7: content
                "\"FLAG_TYPE\" INTEGER NOT NULL ," + // 8: flag_type
                "\"READ_NUM\" INTEGER," + // 9: read_num
                "\"PRAISE_NUM\" INTEGER," + // 10: praise_num
                "\"COMMENT_NUM\" INTEGER," + // 11: comment_num
                "\"HAS_PRAISED\" INTEGER);"); // 12: has_praised
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"WEITOUTIAO_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, WeitoutiaoInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long user_id = entity.getUser_id();
        if (user_id != null) {
            stmt.bindLong(2, user_id);
        }
 
        String username = entity.getUsername();
        if (username != null) {
            stmt.bindString(3, username);
        }
 
        String where = entity.getWhere();
        if (where != null) {
            stmt.bindString(4, where);
        }
 
        java.util.Date time = entity.getTime();
        if (time != null) {
            stmt.bindLong(5, time.getTime());
        }
 
        String img_path = entity.getImg_path();
        if (img_path != null) {
            stmt.bindString(6, img_path);
        }
 
        String img_path_list = entity.getImg_path_list();
        if (img_path_list != null) {
            stmt.bindString(7, img_path_list);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(8, content);
        }
        stmt.bindLong(9, entity.getFlag_type());
 
        Integer read_num = entity.getRead_num();
        if (read_num != null) {
            stmt.bindLong(10, read_num);
        }
 
        Integer praise_num = entity.getPraise_num();
        if (praise_num != null) {
            stmt.bindLong(11, praise_num);
        }
 
        Integer comment_num = entity.getComment_num();
        if (comment_num != null) {
            stmt.bindLong(12, comment_num);
        }
 
        Boolean has_praised = entity.getHas_praised();
        if (has_praised != null) {
            stmt.bindLong(13, has_praised ? 1L: 0L);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, WeitoutiaoInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long user_id = entity.getUser_id();
        if (user_id != null) {
            stmt.bindLong(2, user_id);
        }
 
        String username = entity.getUsername();
        if (username != null) {
            stmt.bindString(3, username);
        }
 
        String where = entity.getWhere();
        if (where != null) {
            stmt.bindString(4, where);
        }
 
        java.util.Date time = entity.getTime();
        if (time != null) {
            stmt.bindLong(5, time.getTime());
        }
 
        String img_path = entity.getImg_path();
        if (img_path != null) {
            stmt.bindString(6, img_path);
        }
 
        String img_path_list = entity.getImg_path_list();
        if (img_path_list != null) {
            stmt.bindString(7, img_path_list);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(8, content);
        }
        stmt.bindLong(9, entity.getFlag_type());
 
        Integer read_num = entity.getRead_num();
        if (read_num != null) {
            stmt.bindLong(10, read_num);
        }
 
        Integer praise_num = entity.getPraise_num();
        if (praise_num != null) {
            stmt.bindLong(11, praise_num);
        }
 
        Integer comment_num = entity.getComment_num();
        if (comment_num != null) {
            stmt.bindLong(12, comment_num);
        }
 
        Boolean has_praised = entity.getHas_praised();
        if (has_praised != null) {
            stmt.bindLong(13, has_praised ? 1L: 0L);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public WeitoutiaoInfo readEntity(Cursor cursor, int offset) {
        WeitoutiaoInfo entity = new WeitoutiaoInfo();
        readEntity(cursor, entity, offset);
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, WeitoutiaoInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUser_id(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setUsername(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setWhere(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTime(cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)));
        entity.setImg_path(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setImg_path_list(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setContent(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setFlag_type(cursor.getInt(offset + 8));
        entity.setRead_num(cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9));
        entity.setPraise_num(cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10));
        entity.setComment_num(cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11));
        entity.setHas_praised(cursor.isNull(offset + 12) ? null : cursor.getShort(offset + 12) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(WeitoutiaoInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(WeitoutiaoInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(WeitoutiaoInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
